### ISSUE TITLE
A documentation note

### ISSUE THREAD

**Issue by Darklocq** [planbnet/QuickNFO#16]
It's worth mentioning in the docs/description that this will incidentally also display text .NFO files as text. These are common in downloaded file archives, especially of Windows software, as short for "info".  It's actually what I thought this was for, and I'm glad it works. :-)  I don't think I've ever seen a .nfo image file, actually.

**Comment by planbnet** [comment]
NFO files are only text - or rather only characters - it's just that they are arraged to look like images.
